# Generated by Django 2.0.6 on 2018-10-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curtain',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=225)),
                ('category', models.BigIntegerField(db_column='Category')),
                ('model', models.CharField(db_column='Model', max_length=45)),
                ('material1', models.CharField(db_column='Material1', max_length=45)),
                ('material2', models.CharField(db_column='Material2', max_length=45)),
                ('material3', models.CharField(db_column='Material3', max_length=45)),
                ('recommend', models.IntegerField(db_column='Recommend')),
            ],
            options={
                'db_table': 'Curtain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curtaincategory',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
            ],
            options={
                'db_table': 'CurtainCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.BigIntegerField(db_column='EmployeeId', primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=45)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('phone', models.CharField(db_column='Phone', max_length=10)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('memberaccount', models.CharField(blank=True, db_column='MemberAccount', max_length=45, null=True)),
                ('productid', models.BigIntegerField(blank=True, db_column='ProductId', null=True)),
            ],
            options={
                'db_table': 'Favorite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('account', models.CharField(db_column='Account', max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=45)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('phone', models.CharField(db_column='Phone', max_length=10)),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('address', models.CharField(db_column='Address', max_length=45)),
            ],
            options={
                'db_table': 'Member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Memberphoto',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('memberaccount', models.CharField(db_column='MemberAccount', max_length=45)),
                ('photo', models.CharField(db_column='Photo', max_length=45)),
                ('productid', models.BigIntegerField(db_column='ProductId')),
            ],
            options={
                'db_table': 'MemberPhoto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('detailid', models.CharField(db_column='DetailId', max_length=20)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('photo', models.CharField(db_column='Photo', max_length=45)),
                ('price', models.BigIntegerField(db_column='Price')),
                ('material', models.CharField(db_column='Material', max_length=45)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salesorder',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('memberaccount', models.CharField(db_column='MemberAccount', max_length=45)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('ordertime', models.DateField(db_column='OrderTime')),
                ('orderstatus', models.BigIntegerField(db_column='OrderStatus')),
                ('paymentstatus', models.IntegerField(db_column='PaymentStatus')),
                ('productid', models.BigIntegerField(db_column='ProductId')),
                ('photo1', models.CharField(db_column='Photo1', max_length=45)),
                ('photo2', models.CharField(db_column='Photo2', max_length=45)),
                ('photo3', models.CharField(db_column='Photo3', max_length=45)),
            ],
            options={
                'db_table': 'SalesOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('memberaccount', models.CharField(db_column='MemberAccount', max_length=45)),
                ('memberphotoid', models.BigIntegerField(db_column='MemberPhotoId')),
            ],
            options={
                'db_table': 'ShoppingCart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=45)),
                ('category', models.BigIntegerField(db_column='Category')),
                ('recommend', models.IntegerField(db_column='Recommend')),
            ],
            options={
                'db_table': 'Wallpaper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallpapercategory',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
            ],
            options={
                'db_table': 'WallpaperCategory',
                'managed': False,
            },
        ),
    ]
