# Generated by Django 2.0.6 on 2018-12-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('model', models.CharField(db_column='Model', max_length=45)),
                ('material1', models.ImageField(blank=True, upload_to='category')),
                ('material2', models.CharField(db_column='Material2', max_length=45)),
                ('material3', models.CharField(db_column='Material3', max_length=45)),

            ],
            options={
                'db_table': 'Sofa',
                'managed': False,
            },
        ),
    ]
